upstream service1 {
    server service1_1:8199;
    server service1_2:8199;
    server service1_3:8199;
}

server {
    listen 8198;

    # Allow CORS headers to be sent by Nginx
    add_header 'Access-Control-Allow-Origin' 'http://localhost:8198' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Content-Type' always;

    resolver 127.0.0.11 valid=5s;
    
    include /etc/nginx/mime.types;

    # Authentication configuration
    auth_basic "Restricted Access";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Handle the request when the user clicks "REQUEST"
    location /request {
        proxy_pass http://service1;
    }

    # Handle stop button (stop the container)
    # location /stop {
    #     access_log /dev/null;
    #     error_log /dev/null;
    #     # exec /bin/sh -c "docker-compose down && exit";
    # }
}
